"""initial migration

Revision ID: d84ad824cd42
Revises: 
Create Date: 2024-10-24 20:56:50.117174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84ad824cd42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_types')),
    sa.UniqueConstraint('type_name', name=op.f('uq_animal_types_type_name'))
    )
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmers')),
    sa.UniqueConstraint('email', name=op.f('uq_farmers_email'))
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('animal_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], name=op.f('fk_animals_animal_type_id_animal_types')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_animals_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animals')),
    sa.UniqueConstraint('name', name=op.f('uq_animals_name'))
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('feed_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_feeds_animal_id_animals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds'))
    )
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('checkup_date', sa.DateTime(), nullable=False),
    sa.Column('treatment', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('vet_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_health_records_animal_id_animals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_productions_animal_id_animals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productions'))
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_sales_animal_id_animals')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_sales_production_id_productions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('productions')
    op.drop_table('health_records')
    op.drop_table('feeds')
    op.drop_table('animals')
    op.drop_table('farmers')
    op.drop_table('animal_types')
    # ### end Alembic commands ###
